Repository wecode-bootcamp-korea/22-1st-Villy-frontend, pull requests merged in 2021-07, with the labels that each got.

#1 [22-1st-Villy-frontend] Setting 수정 사항 반영
  src/Routes.js
  src/styles/common.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#9 [22기 최창원] 🚨전체 세팅 파일 수정 및 추가
  public/index.html
  src/config.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: Accepted

#4 [22기 이윤경] Nav 페이지 코드리뷰 확인 후 수정 완료했습니다!
  public/images/logo.png
  public/images/test.jpeg
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Main/Main.js
Labels: Status: Accepted

#2 [22기 이수정] Product 레이아웃 완료
  public/data/ProductData.json
  public/images/bone.svg
  public/images/hairstyle.svg
  public/images/height.svg
  public/images/producHeader.jpg
  public/images/productSample01.jpg
  public/images/therapy.svg
  public/index.html
  src/config.js
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
  src/pages/Product/ProductCard/ProductCard.js
  src/pages/Product/ProductCard/ProductCard.scss
  src/pages/Product/ProductCard/ProductDescription/ProductDescription.js
  src/pages/Product/ProductCard/ProductDescription/ProductDescription.scss
  src/pages/Product/ProductCard/ProductIcon/ProductIcon.js
  src/pages/Product/ProductCard/ProductIcon/ProductIcon.scss
  src/pages/Product/ProductModal/ProductModal.js
  src/pages/Product/ProductModal/ProductModal.scss
  src/styles/common.scss
Labels: Status: Accepted

#10 [22기 이수정] 추천제품 레이아웃
  src/Routes.js
  src/config.js
  src/pages/Recommend/Recommend.js
  src/pages/Recommend/Recommend.scss
Labels: Status: 리뷰 요청

#14 [22기 최창원] Nav바 추가 기능 구현(수정에 수정했습니다!)
  public/images/logo.png
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: Status: 리뷰 요청

#13 [22기 최창원] 상품 상세페이지 기본 레이아웃과 토글 기능 구현했습니다.
  public/data/products/1.json
  public/data/products/10.json
  public/data/products/11.json
  public/data/products/2.json
  public/data/products/3.json
  public/data/products/4.json
  public/data/products/5.json
  public/data/products/6.json
  public/data/products/7.json
  public/data/products/8.json
  public/data/products/9.json
  src/Routes.js
  src/config.js
  src/pages/Main/Footer/FootSlide.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
Labels: Status: Accepted

#15 [22기 이윤경] Cart 페이지 코드리뷰 확인 후 수정 완료했습니다!
  public/data/CartListData.json
  public/favicon.ico
  public/images/ListNull.png
  public/images/pill1.jpeg
  public/images/productSample01.jpg
  src/Routes.js
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/Order/Order.js
  src/pages/Cart/Order/Order.scss
  src/pages/Login/Login.js
  src/pages/ProductDetail/ProductDetail.js
Labels: Status: 리뷰 요청

#17 [22기 이수정] Product category 기능 구현
  public/data/ProductData.json
  src/config.js
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
  src/pages/Product/ProductCard/ProductCard.js
  src/pages/Product/ProductCard/ProductIcon/ProductIcon.js
  src/pages/Product/ProductCategory/ProductCategory.js
  src/pages/Product/ProductCategory/ProductCategory.scss
  src/utils/productUtils.js
Labels: Status: 리뷰 요청

#18 [22기 최창원] validation 함수와 request 함수 분리 완료 엉엉 ㅠㅠ 😭
  src/pages/Signup/Signup.js
  src/pages/Signup/Validation.js
Labels: Status: 리뷰 요청

#19 [22기 이수정] ProductCard Link 연결
  public/data/ProductData.json
  src/Routes.js
  src/pages/Cart/Cart.js
  src/pages/Product/Product.js
  src/pages/Product/ProductCard/ProductCard.js
  src/pages/Product/ProductCard/ProductCard.scss
Labels: Status: 리뷰 요청

#20 [22기 이수정] 추천제품 Survey 레이아웃, 스타일 완성, 기능 구현중
  src/components/Nav/Nav.js
  src/pages/Main/Main.js
  src/pages/Recommend/Recommend.js
  src/pages/Recommend/Recommend.scss
  src/pages/Recommend/Survey/Survey.scss
  src/pages/Recommend/Survey/Survey01.js
  src/pages/Recommend/Survey/Survey02.js
  src/pages/Recommend/Survey/Survey03.js
  src/pages/Recommend/Survey/Survey04.js
  src/pages/Recommend/Survey/SurveyButton/SurveyButton.js
  src/pages/Recommend/Survey/SurveyWelcome.js
  src/pages/Recommend/Survey/SurveyWelcome.scss
Labels: Status: 수정 요청

#21 레코멘드 완성😂❤️😍😍😍❤️❤️
  src/Routes.js
  src/pages/Product/Product.js
  src/pages/Recommend/Recommend.js
  src/pages/Recommend/Survey/Survey04.js
Labels: Status: Accepted
